# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run: |
          echo "I am trying something new here"
          echo $MONGO_USER > filechick
          echo export CURDIR=`pwd` >> $BASH_ENV
          cat filechick
      - run: docker run -v ${CURDIR}/filechick:/filechick alpine sh -c "cat /filechick"
          

workflows:
  # Name the workflow "execute"
  otomato:
    jobs:
      - build
