# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run: |
          echo "I am trying something new here"
                
      - run: docker run alpine sh -c "cat /etc/*-release"
          

workflows:
  # Name the workflow "execute"
  otomato:
    jobs:
      - build
